name: "Branch Naming Convention"

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
      - 'wip/*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          # Obtém o nome da branch
          branch_name=${GITHUB_REF#refs/heads/}
          
          # Verifica se o nome da branch segue a convenção
          if [[ ! $branch_name =~ ^feature/[A-Z0-9-/]+/.*$ ]] && \
             [[ ! $branch_name =~ ^fix/[A-Z0-9-/]+/.*$ ]] && \
             [[ ! $branch_name =~ ^release/.*$ ]] && \
             [[ ! $branch_name =~ ^hotfix/[A-Z0-9-/]+/.*$ ]] && \
             [[ ! $branch_name =~ ^support/[A-Z0-9-/]+/.*$ ]]; then
            echo "ERROR: O nome da branch '$branch_name' não segue a convenção de nomenclatura."
            echo "Por favor, consulte o arquivo README para mais informações sobre a convenção de nomenclatura de branches."
            echo "A equipe do AnkiDroid agradece pela sua colaboração!"
            exit 1
          fi
