name: Firebase Test Lab CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Install jq
        run: sudo apt-get install jq

      - name: Write and Process Secret
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT }}' > temp.json
          jq . temp.json > service-account-key.json

      - name: Validate JSON
        run: jq . service-account-key.json

      - name: Build and Run Espresso Tests
        run: |
          ./gradlew AnkiDroid:assembleDebug
          ./gradlew AnkiDroid:packageFullDebugAndroidTest

      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'tests-config-test.yml:android-pixel-5'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_64 }}