name: Distribute to Firebase

on:
  workflow_run:
    workflows: ["Android Lint", "Android Unit Tests"]
    branches:
      - main
      - develop
    types:
      - completed
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-firebase-distribution:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Debug APKs
        run: ./gradlew assembleDebug

      - name: Distribute armeabi-v7a APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: AnkiDroid/build/outputs/apk/full/debug/AnkiDroid-full-armeabi-v7a-debug.apk
          releaseNotes: "PR #${{ github.event.pull_request.number }} - SHA: ${{ github.sha }}"

      - name: Distribute arm64-v8a APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: AnkiDroid/build/outputs/apk/full/debug/AnkiDroid-full-arm64-v8a-debug.apk
          releaseNotes: "PR #${{ github.event.pull_request.number }} - SHA: ${{ github.sha }}"

      - name: Distribute x86 APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: AnkiDroid/build/outputs/apk/full/debug/AnkiDroid-full-x86-debug.apk
          releaseNotes: "PR #${{ github.event.pull_request.number }} - SHA: ${{ github.sha }}"

      - name: Distribute x86_64 APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: AnkiDroid/build/outputs/apk/full/debug/AnkiDroid-full-x86_64-debug.apk
          releaseNotes: "PR #${{ github.event.pull_request.number }} - SHA: ${{ github.sha }}"
