name: GitFlow PR Title Validation for Main Branches

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - main
      - master

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" == "develop" && ! "$PR_TITLE" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "error: PRs da branch 'develop' para 'main' devem ser do tipo 'release' e seguir o formato 'release/x.y.z'."
            exit 1
          fi
          
          if [[ ! "$PR_TITLE" =~ ^(feature: \[[a-zA-Z0-9]+\] |fix: \[[a-zA-Z0-9]+\] |hotfix: \[[a-zA-Z0-9]+\] |support: \[[a-zA-Z0-9]+\] |release/[0-9]+\.[0-9]+\.[0-9]+$) ]]; then
            echo "error: O título do PR não segue a nomeclatura do GitFlow."
            echo "Por favor, use uma das seguintes nomeclaturas: feature: [ID do Ticket] Descrição, fix: [ID do Ticket] Descrição, hotfix: [ID do Ticket] Descrição, support: [ID do Ticket] Descrição."
            exit 1
          fi

          if [[ "$BASE_BRANCH" == "develop" && ! "$PR_TITLE" =~ ^(feature: \[[a-zA-Z0-9]+\] |fix: \[[a-zA-Z0-9]+\] |support: \[[a-zA-Z0-9]+\] ) ]]; then
            echo "error: PRs com base na branch 'develop' devem ser do tipo 'feature', 'fix' ou 'support'."
            exit 1
          fi

      - name: Add comment to PR
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const message = "O título do PR não segue as convenções de nomenclatura estabelecidas. Não fique triste, você está quase lá! 🌟\n" +
            "Por favor, use um dos seguintes formatos para o título do seu PR: \n" +
            "- `feature: [ID do Ticket] Descrição Concisa`\n" +
            "- `fix: [ID do Ticket] Descrição Concisa`\n" +
            "- `release/x.y.z` (para PRs da branch 'develop' para 'main')\n" +
            "- `hotfix: [ID do Ticket] Descrição Concisa`\n" +
            "- `support: [ID do Ticket] Descrição Concisa`\n\n" +
            "Obrigado por ajudar o Anki a ser um app melhor! O time AnkiDroid agradece a sua contribuição! 🙏";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });
