name: Simplified Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/**'
      - 'AnkiDroid/**'
      - 'api/**'
      - 'lint-rules/**'
      - 'annotations/**'
      - '**/*.gradle'
      - 'gradle/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: JUnit Tests (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Verify JDK17
        run: java -fullversion 2>&1 | grep '17.0'
        shell: bash

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-home-cache-cleanup: true

      - name: Gradle Dependency Download
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./gradlew robolectricSdkDownload --daemon

      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoUnitTestReport --daemon

      - uses: codecov/codecov-action@v3
        with:
          verbose: true
